name: Terraform Plan

on:
  workflow_dispatch: 
  
jobs: 
  terraform:
    runs-on: ubuntu-latest

    steps: 
    - name: Check Out Repository
      uses: actions/checkout@v2

    - name: Setup Azure CLI
      uses: azure/login@v1.4.0
      with: 
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Check Azure Credentials
      run: az account show

    - name: Install terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.9.5
    
    - name: Initialize terraform
      run: terraform init

    - name: terraform plan
      run: terraform plan
